### ISSUE TITLE
Connect to engine using HTTP headers

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#10]
This will enable support for:

* JWT (or any other schema our users might have for) authentication
* Separating engine sessions

**Comment by FredrikFolkesson** [comment]
I guess we want JWT support and not https?

**Comment by peol** [comment]
HTTPS (i.e. WSS) is already supported AFAIK.

**Comment by FredrikFolkesson** [comment]
@peol But not supported in engine yet?

**Comment by peol** [comment]
Engine doesn't need to support it, but you might have to go through a reverse proxy (like we have in assisted prescription and urbanization) to access your engine. It's using secure websocket between corectl and the proxy, but a regular websocket internally (from proxy to engine).
