### ISSUE TITLE
No error message when engine has expired

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#106]
Using corectl against an expired engine throws no valuable error message. 

E.g. trying to build an application returns app not found. I would expect it to tell me that the engine has expired.

Related to #90

**Comment by FredrikFolkesson** [comment]
@sublibra when I run a build command `corectl.exe build -a=test.qvf --engine=localhost:9076` with an old engine (12.251) on master I get an message like this: `License error: This engine has expired (12001)`

**Comment by sublibra** [comment]
I can't reproduce this. I will watch out for this error again and be more thorough in describing the setup next time.
