### ISSUE TITLE
Add clarification on what is saved

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#110]
When adding data to an application such as connections, there is no output if connections were saved or not. Instead there is a "Saving...Done" which refers to the application. In cases where no connection is saved the output "Saving...Done" could be misleading since the user might take that as an incorrect connection were saved.

Example:
$ corectl.exe set connections --config config-with-connections.yaml
Saving...Done

vs

$ corectl.exe set connections --config config-with-incorrect-connection.yaml
Saving...Done

Consider adding error message if connection is not saved as well as changing the "Saving...Done" to what is being saved.

**Comment by gabbaxx** [comment]
Printout now states that the app is saved
