### ISSUE TITLE
"Free text" way of setting the connection string of a connection

### ISSUE THREAD

**Issue by gabbaxx** [qlik-oss/corectl#111]
Currently there is support to define the connection string of a connection in the config file using the settings attribute:
connections:
  my-connection:
    type: my-connector
    settings:
      param1: value
      param2: value

For some connectors a format with a raw strings is needed:
connections:
  my-connection:
    type: my-connector
    settings-string: special settings like json, etc

**Comment by FredrikFolkesson** [comment]
How is this used by the qix api? Why can't you have param1 be your string?

**Comment by FredrikFolkesson** [comment]
closed with #114
