### ISSUE TITLE
Support nested objects

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/corectl#120]
It would be nice to be able to define objects that are part of a parent-child hierarchy. In a sense concept, a parent sheet having multiple children such as sheet objects.

You can today set/get the parent and all its children via Get/SetFullPropertyTree.

**Comment by axelssonHakan** [comment]
Design: support `GenericObjectEntry`and `GenericObjectProperties`. coreCtl will understand what to use depending on JSON structure

**Comment by FredrikFolkesson** [comment]
Closed with #130
