### ISSUE TITLE
Do we want to include system tables?

### ISSUE THREAD

**Issue by FredrikFolkesson** [qlik-oss/corectl#126]
Including the system tables crashed on some apps since `GetTableAndKeys` did not return them. Thus we removed them in #123 

But it not clear why they were added in the first place, we should understand why they were added and if we need to add them back in and change how we handle system tables instead of just not including them.

@gabbaxx probably knows

**Comment by wennmo** [comment]
Can we close this @gabbaxx

**Comment by wennmo** [comment]
Closing issue, lets reopen or file a new issue if we find that this is needed.
