### ISSUE TITLE
Tab completion issues using bash and windows/linux

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#170]
The following incorrect behaviour was experienced █ = cursor position while executing tab completion:

```bash
corectl get dimension --app █
linux:lists dir
windows: lists app (with ^M)

corectl get dimension █ -a "Sales Discovery"
linux:lists dir
windows: -a

corectl get meta -a █
linux: lists dir
windows: lists app (With ^M)

med app i corectl.yml
corectl get dimension properties █
windows: lists dimensions
linux: lists dir
```

**Comment by sublibra** [comment]
Latest build: 1/4 16:26

**get connection**
*Linux bash*
bgk@Ubuntu-test3:~/tmp$ corectl get connections 
+--------------------------------------+------+--------+
|                  Id                  | Name |  Type  |
+--------------------------------------+------+--------+
| 98dbb6e0-e2c3-4856-b2a2-16bda21c329c | data | folder |
+--------------------------------------+------+--------+
bgk@Ubuntu-test3:~/tmp$ corectl get connection bash: ${1[@]}: bad substitution

*Linux zsh*
works

**Comment by wennmo** [comment]
@sublibra Can you check that you are sourcing the latest completion? `${1[@]}: bad substitution` should be fixed in the `0.5.0` release.

**Comment by sublibra** [comment]
Looking good on clean computer running 0.5.0! :fireworks:

**Comment by sublibra** [comment]
Test Ok
