### ISSUE TITLE
Investigate publish to brew and linux repos

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#177]
Investigate possibility to publish corectl to brew and linux repos (snap or simiar).

Assess possibilities (conflicting packages etc)
Propose distribution channel (e.g. snap, brew, deb, rpm)
Create tasks for the work.

**Comment by sublibra** [comment]
Maybe use something like
https://snapcraft.io/

**Comment by wennmo** [comment]
`corectl` is using `goreleaser` for creating a release, and there seems to be support for publishing to both homebrew and snapcraft built-in.

Publish to homebrew:
https://goreleaser.com/homebrew/

Publish to snapcraft:
https://goreleaser.com/snapcraft/

**Comment by sublibra** [comment]
Awesome!

**Comment by glooms** [comment]
GoRealeser cannot release to homebrew-core but instead releases homebrew-taps which are not accepted into official homebrew repositories. More about taps: [https://docs.brew.sh/Taps.html](https://docs.brew.sh/Taps.html)

Although sparsely documented, GoReleaser seems to support snapcraft. Although, it seems pretty easy to publish to snapcraft without GoReleaser aswell: [https://docs.snapcraft.io/go-applications/7818](https://docs.snapcraft.io/go-applications/7818)

**Comment by glooms** [comment]
Could not quite figure out how to publish things at homebrew-core but it seems that the information can be found at:
[https://docs.brew.sh/Formula-Cookbook](https://docs.brew.sh/Formula-Cookbook)

**Comment by glooms** [comment]
To publish to brew seems pretty straight forward.

`$brew create https://path.to.tarball --set-name=qlik-corectl`

The `set-name` flag is need due to namespace collision with corectl, as was expected.
Seems like the version can either be auto-detected from the url, added by tag (which might be a cmd flag although I've not found clarity on this yet) or specified in the formula (ruby file).

From there you add some additional info in the qlik-corectl.rb file that was generated according, just follow the [cookbook](https://docs.brew.sh/Formula-Cookbook), adding tests, homepage, description and such.
When all is done fork the brew repo, add the "formula" and make a PR.

**Comment by glooms** [comment]
For `snap` it seems like the steps are the following:

```bash
cd ~/git/corectl
snapcraft init
```

this creates a directory in the repo called snap with `snapcraft.yaml` in it. This file pretty much specifies everything, version, description. Info about how and what to configure is [here](https://docs.snapcraft.io/go-applications/7818).

After the yaml file has been modified, running `snapcraft` creates the snap.
To release the snap you have to have an account and reserve a namespace, after which you can push the release with:

`snapcraft push mygosnap_*.snap`

(with appropriate flags of course).

**Comment by sublibra** [comment]
We should look into what possibilities exists for Windows as well. 
Maybe: https://chocolatey.org/

**Comment by glooms** [comment]
As `corectl` does not really support `PowerShell` & `cmd` maybe it is a bit strange to have it available in `chocolatey`. You still have to use it in `git-bash` or `WSL`.

It also seems like the software stack used by `chocolatey` includes `XML` and `NuGet` which combined with the somewhat terse documentation of how to actually create and release packages makes using `chocolatey` a bit harder than snap and brew.

**Comment by glooms** [comment]
Create issues to actually publish, investigation terminated.
