### ISSUE TITLE
Don't rely on GetAllInfos for Dimensions and Measures

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/corectl#194]
When listing dimensions or measures via `corectl get dimensions/measures` we list all objects and extract objects based on qType == measure/dimension.

However a GenericMeasure or GenericDimension can have whatever qType the developer choose to set. So if a developer choose to create a GenericMeasure with qType `poop` it will not be listed through the `get measures`command.

We should instead create a GenericObject with a qMeasureListDef and list the qInfo/qId property.

**Comment by hrigner** [comment]
Soo.. how does the measurelist know that the measure with qType `poop` is a measure?

**Comment by peol** [comment]
Engine has two types to track an object. `qType` and `qGenericType`: https://core.qlik.com/services/qix-engine/apis/qix/definitions/#objectinterface One will always be "GenericMeasure" in that case

**Comment by gabbaxx** [comment]
We now use a session object with a qDimensionListDef: { qType:"dimension", qData: ...} instead of getAllInfos to list the dimensions. This allows us to include the title of the object. However we still can't list dimensions/measures with different qTypes. (I believe qType in the properties corresponds to the qGenericType in the objectinterface)

**Comment by sublibra** [comment]
Seems like we are partly on the way. @mindspank - what is the priority on this? Is this corner cases only? It seems like we are promoting an incorrect way of working if we allow for working with dimensions/measures with incorrect type.

**Comment by mindspank** [comment]
In a Sense context it's a corner case as the Sense client will always define their types as `dimension` and `measure`.

Outside the Sense client I would assume a developer can choose her own naming on objects as she pleases.

**Comment by glooms** [comment]
We now enforce all measures and dimensions to have the qType measure and dimension, respectively, and GetAllInfos is only used to list objects. We don't support the qType `poop` case since there doesn't seem to be a strong enough reason for it.

**Comment by mindspank** [comment]
We should document this as this is an opinion the tool enforces on the user

**Comment by glooms** [comment]
We can document it further but there is a clear error message if an (in corectl's opinion) erroneous type is set.

```
validation error in file temp.json: dimensions must have qType: dimension
```
