### ISSUE TITLE
Set Measures/Dimensions does not accept blank qId

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/corectl#195]
```
{
    "qInfo":{
        "qType":"measure",
        "qId":""
    },
    "qMetaDef":{
        "title":"Testing",
        "description":"",
        "tags":[]
    },
    "qMeasure":{
        "qLabel":"Testing",
        "qDef":"Count(Dim1)",
        "coloring":{}
    }
}
```
If not specifying an id in `qInfo/qId` corectl will throw an error with:
`Missing qInfo qId attribute ./measures.json`

I would expect: corectl to accept empty ids as the engine service will then assign a available id.

**Comment by wennmo** [comment]
The `qId` is required today to check whether a measure/dimension etc already exists. If allowing `qId` to be omitted then `corectl` would need to persist the identifier for created objects.

**Comment by mindspank** [comment]
Can't we rely on GetObject - > if fail > Create Object else > GetObject > SetProperties

Kind Regards,
Alexander Thor

________________________________

**Comment by wennmo** [comment]
`GetObject` would still require `corectl` to pass a `qId` though.

If a `qId` is not specified in the json file then `corectl` will need to persist the identifier locally when the object is created i.e. the `qId` returned by Engine.

I agree that this is something that we should try to support, and it could probably be handled similar to how we handle apps being created when Engine is using `ABAC`.

**Comment by mindspank** [comment]
Ye, it threw me off since it deviated from standard engine behavior. Perhaps we can have corectl generate id's?

Kind Regards,
Alexander Thor

________________________________

**Comment by wennmo** [comment]
Yes, that is definitely an option we should look into 👍

**Comment by glooms** [comment]
I think that a robust solution for this problem requires quite a bit of work.
At the very least some ID lookup that maps files to the measures/dimensions they contain and at most a light versioning tool for keeping track of file changes and renames.

It can be done but I think for now the best solution is to simply prohibit blank qIds.
