### ISSUE TITLE
FR: corectl build without reload

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/corectl#199]
It would be nice to be able to run corectl without having to reload the app.
Use case: updating measures, dimensions and objects but I don't want to reload the model.

**Comment by wennmo** [comment]
This is actually possible by running the command `corectl set all`. We are currently looking into replacing this command with a flag to `corectl build` instead e.g. `--no-reload` to make it more intuitive.

**Comment by sublibra** [comment]
As far as I understand this is delivered. @wennmo ?

**Comment by wennmo** [comment]
Yes, it was delivered as part of #207
