### ISSUE TITLE
Publish to brew and snap

### ISSUE THREAD

**Issue by glooms** [qlik-oss/corectl#246]
Publish `corectl 1.0.0` to homebrew and snapcraft using the analysis from #177

**Comment by glooms** [comment]
So it doesn't seem that snap works on wsl: https://forum.snapcraft.io/t/windows-subsystem-for-linux/216/9
Or rather, snap works, but the underlying daemon snapd does not work, so you can't install things with snap.

**Comment by glooms** [comment]
Ran into a proverbial roadblock in the form of the following message from brew audit:
GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

Also, cannot have source only taps at homebrew-core meaning we have to build it from source in our formula which entails a good bit of more work.

**Comment by sublibra** [comment]
Ow. Is it AND or OR requirements?

**Comment by glooms** [comment]
Well, when running the brew audit, these 2 things are "problems" resulting in:
```bash
Error: 2 problems in 1 formula detected
```
So I think they might be mandatory. Also, they encourage the use of brew audit before making a PR to save time for everybody... meaning that you can technically open an PR with an invalid formula but I am guessing it is frowned upon. Building it from source however is probably a minimum to get it close to accepted.

**Comment by glooms** [comment]
Furthermore, to create a tap instead, which is a third party repo that you can have beside homebrew-core, you have to create a repo prefixed with `homebrew-`.

**Comment by glooms** [comment]
I missed this [documentation](https://docs.brew.sh/Acceptable-Formulae) somehow.

Despite that, I think I might have a working, proper, formula, the only drawback is that it seems to crash on one step in the go build about 50% of the time.

**Comment by glooms** [comment]
Publish to snap done, also included publish steps in circleci config.
