### ISSUE TITLE
Add Certificates support for QSEoW Engine

### ISSUE THREAD

**Issue by jparis** [qlik-oss/corectl#299]
Currently the only way to use this with QSEoW is with JWT it seems, but given there's no session management, you burn through the 5 session proxy limit quite quickly. Given the tool and it's usage, I see more customers wanting to use certificates vs going through the proxy anyway, and then you also don't need to worry about session limit.

**Comment by wennmo** [comment]
Added a flag `certificates` in #304 where you can pass a path to a folder containing the PEM certificates. Can be passed by command line flag or part of the [config](https://github.com/qlik-oss/corectl/blob/master/docs/corectl_config.md#certificates).

This functionality will be part of the next release of `corectl`.
