### ISSUE TITLE
Add support for global contexts

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/corectl#315]
When supporting multiple Qlik products e.g. Qlik Core, Qlik Sense Enterprise and QCS etc it would be handy to be able to create and reuse contexts without having to define them in the config file. Similar to the approach in `kubectl`

There is a WIP on this [branch](https://github.com/qlik-oss/corectl/tree/context).

Basically global contexts can be created for a deployment for flags `engine`, `certificates` and `headers`. The flags will be fetched from the global config and applied if not overridden by a local config or cli flags.

**Comment by glooms** [comment]
I've changed my mind regarding context precedence.
I think that the context should have higher precedence than a local config but that we should warn the user in case fields in the config are overridden. At the very least a verbose logging.

**Comment by glooms** [comment]
Wondering how contexts should be created... either simply slurp the things we want from viper when `context create` is called or require the user to specify a config.
In the current state this can be achieved by:
```
corectl context create ctx --config cfg.yml
```

Another thought, how much information should we store in a context? We could store everything from a config + flags if we want, although the paths to other files - glob patterns and such - have to be absolute.
