### ISSUE TITLE
Quiet flag for corectl

### ISSUE THREAD

**Issue by glooms** [qlik-oss/corectl#342]
Would be nice to have a flag `-q` that returns only a list of IDs for a command so that commands can be chained on command line, example:

```bash
> corectl connection ls -q
1234 1235 1236
> corectl connection rm $(corectl connection ls -q)
```

This feature is implemented by docker and is something I use frequently as it is very useful when working with scripts and such.

**Comment by peol** [comment]
Agreed. I use it daily with `docker` and `helm`. But if I had to chose, I'd rather have context support in corectl first 😜

**Comment by glooms** [comment]
It can be implemented in that order if you so please! 😁

**Comment by glooms** [comment]
During this enhancement we should look over what is returned by most of our commands.
Currently I would argue it is too terse. For example:
```
corectl dimension rm "dim"
```
Outputs: "Saving app... Done"
We might want to return the name of dimension removed in this case as well.
