### ISSUE TITLE
Adding recognition of Cyrillic object names to unbuilder.go

### ISSUE THREAD

**Issue by RomanYamp** [qlik-oss/corectl#432]
The code would look like
var matchAllNonAlphaNumeric = regexp.MustCompile(`[^a-zA-Zа-яА-ЯЁё0-9]+`)
Could anyone give a hand with commiting this to the code?
[unbuilder.go.txt](https://github.com/qlik-oss/corectl/files/3689587/unbuilder.go.txt)

**Comment by glooms** [comment]
I'll have a look!

**Comment by glooms** [comment]
@RomanYamp the fix is part of [1.4.1](https://github.com/qlik-oss/corectl/releases/tag/v1.4.1)
