### ISSUE TITLE
Unbuild has undeterministic output

### ISSUE THREAD

**Issue by tsijs** [qlik-oss/corectl#454]
Ls, 

When using the corectl.exe unbuild command with fixed and specified config.yml parameter, it does not result in a deterministic unbuild folder. E.g. sometimes it results in different unbuild versions of the same objects. 
One example: 

Once it exports a title as:

  "title": {
    "qStringExpression": {
      "qExpr": "='This is a test title no. (1)"
    }
  }

When running the unbuild command again this changes sometimes in: 
 "title": "This is a test title no. (1)"

Another example is the id's that are overwritten sometimes. 

Why is this and is there something I can do to prevent the different outputs?

**Comment by wennmo** [comment]
Hi @tsijs, does this occur if you run two `unbuild` commands after each other or is there any modification to the app in between? The `id` or `title` as a property shouldn't change unless the app is being modified.

`"title": "This is a test title no. (1)"` is the evaluated version of the property i.e. part of the layout of the object.

**Comment by tsijs** [comment]
There is no modification in between, I unbuild an app on the sense desktop version twice justafter each other and the output is not deterministic.

Just to be specific on something you mentioned: when the app is modified, all qids/cids could change or just the ones of the modified items?

I don't fully understand the second part of your response. Do you mean that when interpreted, they are equivalent? The two examples I provided are inside a json object after unbuilding. And it seems for now that at random times it prefers one over the other.

**Comment by wennmo** [comment]
If there is no modification to the app in between the two unbuilds there should not be any changes in the properties, so this is something we need to investigate further. Is the app open in sense desktop while you are unbuilding the app?

> Just to be specific on something you mentioned: when the app is modified, all qids/cids could change or just the ones of the modified items?

If the app is being modified using the sense desktop client the `qId`s might change e.g. if editing sheets or changing visualizations, however that is not something that should be triggered through `corectl`.

> I don't fully understand the second part of your response. Do you mean that when interpreted, they are equivalent? The two examples I provided are inside a json object after unbuilding. And it seems for now that at random times it prefers one over the other.

The property (`title`) you referred to is a [StringExpression](https://help.qlik.com/en-US/sense-developer/February2019/Subsystems/EngineAPI/Content/Sense_EngineAPI/GenericObject/PropertyLevel/StringExpresssion.htm) which means that if performing a `layout` on that object will return the evaluated result for that expression which is `"title": "This is a test title no. (1)"`.

I have not yet been able to reproduce the problem you are experiencing. Is it possible for you to provide us with a json object that can trigger the problem?

**Comment by tsijs** [comment]
> If there is no modification to the app in between the two unbuilds there should not be any changes in the properties, so this is something we need to investigate further. Is the app open in sense desktop while you are unbuilding the app?

No, but the desktop sense program is running, since the sense engine needs to be running for corectl to work.

> If the app is being modified using the sense desktop client the qIds might change e.g. if editing sheets or changing visualizations, however that is not something that should be triggered through corectl.

Could you be a little more specific on the intended behavior of the ids in case of change. E.g. if sheet 1 is changed, does this influence the ids on sheet 2?

> The property (title) you referred to is a StringExpression which means that if performing a layout on that object will return the evaluated result for that expression which is "title": "This is a test title no. (1)".

Ok, thanks for the explanation, then I understood it correctly. 

> I have not yet been able to reproduce the problem you are experiencing. Is it possible for you to provide us with a json object that can trigger the problem?

I have a qvf that if unbuilded twice, it produces this error. Though it seems to be hard to reproduce in small examples indeed. Do you have some contact information I could send this qvf to?

**Comment by wennmo** [comment]
> Could you be a little more specific on the intended behavior of the ids in case of change. E.g. if sheet 1 is changed, does this influence the ids on sheet 2?

If the sheets share objects/visualizations that might occur I guess, since the objects are children to a sheet. That would however be more Sense Client implementation, which is not really my area.

> I have a qvf that if unbuilded twice, it produces this error. Though it seems to be hard to reproduce in small examples indeed. Do you have some contact information I could send this qvf to?

If you have a qvf that you can share that would be great! If you are part of the Qlik Branch Slack, you can DM me there.

**Comment by wennmo** [comment]
We have been unable to reproduce this problem using the same versions and app as @tsijs . It was also not reproducible for the reporter after installing a later version of Qlik Sense Desktop.

If this problem reappears please reopen the issue.
