### ISSUE TITLE
Special characters not unbuilding correctly

### ISSUE THREAD

**Issue by tsijs** [qlik-oss/corectl#497]
When variables contain special chars and super-subscripts, they will not be unbuild-build properly.

**Comment by glooms** [comment]
Hi tsijs, could you provide steps to reproduce this behavior so I can have a look?

**Comment by glooms** [comment]
@tsijs I tried with unicode sub/superscripts and special characters from the cyrillic alphabet and could not reproduce the error. I need more information about how this error was achieved in order to solve it.

Output after build + unbuild + build:
```
+--------------+-------+
|      ID      | Title |
+--------------+-------+
| variable-abc | x¹²³  |
| variable-xyz | x₀₁₂  |
+--------------+-------+
```

**Comment by glooms** [comment]
Closing this issue, just reopen if you can provide information for reproducing.

**Comment by tsijs** [comment]
Thanks for the response, and sorry for taking this long to reply. For the sake of completeness of documentation: This issue occured for me for the titles of sheets. I won't have time to test this atm though, so leaving this closed for now is fine by me.
