### ISSUE TITLE
Content library references are automatically changed to in-app references for desktop installation

### ISSUE THREAD

**Issue by tsijs** [qlik-oss/corectl#501]
This is probably not at core a corectl problem, but content library references are automatically changed to in-app references for desktop installation after a build-unbuild. This is unwanted since the in-app content does not come along with an unbuild and will therefore break the reference for a next build.

**Comment by gabbaxx** [comment]
Cross-installation cases involving content library references are unfortunately not supported by corectl

**Comment by sublibra** [comment]
Closing this since we will not support this at the moment.
