### ISSUE TITLE
No sheets titles in app object ls functions

### ISSUE THREAD

**Issue by RomanYamp** [qlik-oss/corectl#534]
Function `app object ls` returns sheets without title.
`App object properties` for a specific sheet returns json with sheet title.

**Comment by wennmo** [comment]
Hi @RomanYamp, thanks for submitting the issue. 

The unbuilder correctly parses `title` but not when listing objects. Looks like we need to update the parsing of `qMetaDef`: https://github.com/qlik-oss/corectl/blob/master/internal/object.go#L60
