### ISSUE TITLE
Apps command doesn't work in 0.3

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#58]
Res:

Error: unknown command "apps" for "qli"
Run 'qli --help' for usage.
unknown command "apps" for "qli"

Also doesn't show up in help

**Comment by wennmo** [comment]
Seems like you are running an older version of `corectl`, perhaps from `~/home/bin` folder?

**Comment by sublibra** [comment]
It was not enough to change version number in the readme links. The windows exec changed name as well.. No fix needed
