### ISSUE TITLE
Add .rc file for most common parameters

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#71]
Add possibility to set common parameters such as (--no-save) in a configuration file in the users home directory

DoD
- [ ] Decide upon supported parameters
- [ ] Decide file location, name, design
- [ ] Document and create example config

**Comment by wennmo** [comment]
Currently we don't see any value of setting global settings for this tool, since it might lead to unexpected behaviour if we are falling back to a global config with regards to e.g. `--no-save`. Closing issue for now, but could be reopened if we find a valid use-case for it.
