### ISSUE TITLE
Add support for json output

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#74]
Add support for json output of all relevant commands from the tool

**Comment by FredrikFolkesson** [comment]
We support it in `apps` command now, should we support it in more commands? @gabbaxx

**Comment by axelssonHakan** [comment]
Adding to just apps solves only one smal Use Case. If would be very powerful if any return value from QIX could be sent to stdout. The default output should still be `table` but option -o json should output the "RAW" json from engine

**Comment by FredrikFolkesson** [comment]
We now have JSON output for `get apps`, `get dimensions`,`get dimension`, `get measures`,`get measure`, `get objects` and `get object`

If we want JSON output for any of our other commands this issue could be reopened.
